# Generated by Django 4.0.2 on 2022-02-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='ports',
            field=models.CharField(max_length=200),
        ),
    ]
