# Generated by Django 4.0.2 on 2022-02-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_alter_scans_ports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scans',
            new_name='scan',
        ),
    ]
