# Generated by Django 4.0.2 on 2022-02-25 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scan', '0004_delete_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorieScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='scan',
            fields=[
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('host', models.GenericIPAddressField()),
                ('ports', models.JSONField()),
                ('date', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.categoriescan')),
            ],
        ),
    ]
