# Generated by Django 4.0.2 on 2022-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriescan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
