# Generated by Django 4.0.2 on 2022-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0008_alter_categoriescan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriescan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
