# Generated by Django 4.0.2 on 2022-02-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0009_alter_categoriescan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriescan',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scan',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scan.categoriescan'),
        ),
    ]
