# Generated by Django 4.0.2 on 2022-03-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0010_alter_categoriescan_id_alter_scan_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='host',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='ports',
        ),
        migrations.CreateModel(
            name='hostScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('ports', models.JSONField()),
                ('scan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scan.scan')),
            ],
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('host', models.GenericIPAddressField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scan.categoriescan')),
            ],
        ),
    ]
