# Generated by Django 4.0.2 on 2022-03-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0011_remove_scan_host_remove_scan_ports_hostscan_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostscan',
            name='portsUDP',
            field=models.JSONField(default='{}'),
        ),
    ]
